version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sms_reminders
      POSTGRES_USER: sms_user
      POSTGRES_PASSWORD: sms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://sms_user:sms_password@postgres:5432/sms_reminders
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    env_file:
      - .env

  celery-worker:
    build: .
    command: celery -A scheduler.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://sms_user:sms_password@postgres:5432/sms_reminders
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - backend
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A scheduler.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://sms_user:sms_password@postgres:5432/sms_reminders
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
      - backend
    env_file:
      - .env

volumes:
  redis_data:
  postgres_data: